<?php
/**
 * @var \Comwrap\Cookiebot\ViewModel\CookiebotViewModel $viewModel
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
$viewModel = $block->getViewModel();
?>
<?php if ($viewModel->isEnabled()): ?>
    <script type="text/x-magento-init">
            {
                "*": {
                    "Comwrap_Cookiebot/js/cookiebot": {
                        "cookieBotUrl": "<?= $escaper->escapeUrl($viewModel->getCookiebotUrl()) ?>",
                        "accountId": "<?= $escaper->escapeHtmlAttr($viewModel->getCookiebotId()) ?>",
                        "asyncMode": <?= /** @noEscape  */ $viewModel->getAsyncMode() ?>
                    }
                }
            }
    </script>
<?php endif; ?>

